Updating thruhole firmware
tetrabiodistributed/papra-pcba-firmware pull request #11
Opened 2024-03-10 22:16 UTC by mmroden

Adding in the thruhole firmware and updating the readme appropriately

2024-03-11 16:16 UTC, mmroden commented on README.md
>  Firmware is intended to be loaded on this PCB: https://github.com/tetrabiodistributed/PAPRA-PCB
Should be fixed now

2024-04-04 14:44 UTC, capsulecorplab requested changes

2024-04-04 14:44 UTC, capsulecorplab commented on README.md
> +# papra-pcb-firmware for surface mount boards
`papra-pcb-firmware` s/b `papra-pcba-firmware`

2024-04-04 14:44 UTC, capsulecorplab commented on README.md
> +To use this repo, you will need a built PAPRA pcb, either the surface mount version or the thruhole version.  Check this repo for more information:
`PCB` s/b `PCB Assembly`

2024-04-04 14:44 UTC, capsulecorplab commented on README.md
> +Firmware is intended to be loaded on this PCB: https://github.com/tetrabiodistributed/PAPRA-PCBA
`PCB` s/b `PCB Assembly`

2024-04-04 16:14 UTC, capsulecorplab approved these changes
LGTM

2024-04-04 16:17 UTC, merged